### ISSUE TITLE
Move to Flint organization.

### ISSUE THREAD

**Issue by henrikbjorn** [Stampie/HBStampieBundle#14]
To allow more people direct access to push.

**Comment by stof** [comment]
Another alternative would be to create a Stampie organization dedicated to Stampie

**Comment by stof** [comment]
@henrikbjorn any news ?

**Comment by henrikbjorn** [comment]
I did the Stampie organization and have invited you, completely forgot about this issue. I'll look into moving stuff tomorrow.

**Comment by henrikbjorn** [comment]
Feel free to move StampieExtra also if you feel like it :)

**Comment by stof** [comment]
@henrikbjorn will do. I'm thinking about renaming the composer package to ``stampie/extra`` too (the namespace already uses Stampie).

**Comment by stof** [comment]
@henrikbjorn you invited me, but you have not given me access to existing repo (I'm a member, not an admin, and not member of any team)

**Comment by stof** [comment]
@henrikbjorn please also update the repo URL on Packagist

**Comment by henrikbjorn** [comment]
Done

tir. 21. feb. 2017 kl. 11.55 skrev Christophe Coevoet <
notifications@github.com>:
